language: node_js
node_js:
  - "node"
install:
  - yarn install
script:
  - yarn lint
deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && now build --public --name yard-frontend --token $NowToken && now alias --token $NowToken
  on:
    branch: travis
