// flow-typed signature: 58c11daa0fafc455c23eab41bbcd4846
// flow-typed version: <<STUB>>/pluralize-ru_v^1.0.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pluralize-ru'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pluralize-ru' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pluralize-ru/lib/pluralize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pluralize-ru/index' {
  declare module.exports: $Exports<'pluralize-ru'>;
}
declare module 'pluralize-ru/index.js' {
  declare module.exports: $Exports<'pluralize-ru'>;
}
declare module 'pluralize-ru/lib/pluralize.js' {
  declare module.exports: $Exports<'pluralize-ru/lib/pluralize'>;
}
